# .github/workflows/keepalive.yml
name: Keep Render Alive
on:
  schedule:
    - cron: "*/5 * * * *"   # mỗi 5 phút
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://p12pass.onrender.com/ > /dev/null
